"""Manas compatibility tests — verified against steward-protocol.

Each test string was run through steward-protocol's actual pipeline:
  - MahaCompression._compute_seed_cached() for seed
  - MahaCompression.decode_samskara_intent() for guna
  - MahaModularSynth('quantum').transform() for attractor → position
  - steward/antahkarana/manas.py affinity chain for ActionType

Ground truth was generated by running steward-protocol from:
  /home/user/steward-protocol (cloned from kimeisele/steward-protocol)

If any test fails, mahaclaw's routing has DIVERGED from steward.
"""
from __future__ import annotations

import pytest

from mahaclaw.manas import (
    _compute_seed,
    _synth_transform,
    _text_to_vibration_sum,
    perceive,
    WORDS,
    MAHA_QUANTUM,
    PARAMPARA,
    QUARTERS,
    HARE_POSITIONS,
    KRISHNA_POSITIONS,
    RAMA_POSITIONS,
)


# =============================================================================
# GROUND TRUTH from steward-protocol (10 diverse strings)
# =============================================================================

GROUND_TRUTH = [
    # (input_text, expected_seed, expected_guna, expected_approach, expected_function, expected_action)
    ("research quantum computing applications", 151408741, "rajas", "genesis", "carrier", "implement"),
    ("fix the login bug in auth.py", 251674628, "rajas", "karma", "carrier", "debug"),
    ("what is the federation governance policy", 101154936, "sattva", "genesis", "source", "implement"),
    ("heartbeat", 67637377, "tamas", "karma", "carrier", "debug"),
    ("deploy the new version to production", 405603, "tamas", "karma", "deliverer", "debug"),
    ("translate this document to German", 50847870, "suddha", "genesis", "carrier", "implement"),
    ("analyze the security vulnerabilities", 234971158, "rajas", "moksha", "carrier", "research"),
    ("create a new agent for data processing", 33816640, "tamas", "karma", "deliverer", "debug"),
    ("status", 33837125, "rajas", "genesis", "carrier", "implement"),
    ("explain how NADI transport works", 234983449, "sattva", "karma", "deliverer", "debug"),
]


class TestSeedCompat:
    """Seed computation must match steward-protocol exactly."""

    @pytest.mark.parametrize("text,expected_seed,_g,_a,_f,_act", GROUND_TRUTH)
    def test_seed_matches(self, text, expected_seed, _g, _a, _f, _act):
        assert _compute_seed(text) == expected_seed


class TestGunaCompat:
    """Guna (from seed % WORDS → quarter) must match steward."""

    @pytest.mark.parametrize("text,_s,expected_guna,_a,_f,_act", GROUND_TRUTH)
    def test_guna_matches(self, text, _s, expected_guna, _a, _f, _act):
        p = perceive(text)
        assert p.guna.value == expected_guna


class TestApproachCompat:
    """Approach (from attractor % WORDS → quarter) must match steward."""

    @pytest.mark.parametrize("text,_s,_g,expected_approach,_f,_act", GROUND_TRUTH)
    def test_approach_matches(self, text, _s, _g, expected_approach, _f, _act):
        p = perceive(text)
        assert p.approach.value == expected_approach


class TestFunctionCompat:
    """Function (from attractor position → HARE/KRISHNA/RAMA) must match steward."""

    @pytest.mark.parametrize("text,_s,_g,_a,expected_func,_act", GROUND_TRUTH)
    def test_function_matches(self, text, _s, _g, _a, expected_func, _act):
        p = perceive(text)
        assert p.function.value == expected_func


class TestActionCompat:
    """ActionType (from affinity chain) must match steward."""

    @pytest.mark.parametrize("text,_s,_g,_a,_f,expected_action", GROUND_TRUTH)
    def test_action_matches(self, text, _s, _g, _a, _f, expected_action):
        p = perceive(text)
        assert p.action.value == expected_action


class TestConstants:
    """Mahamantra constants must match steward-protocol."""

    def test_words(self):
        assert WORDS == 16

    def test_maha_quantum(self):
        assert MAHA_QUANTUM == 137

    def test_parampara(self):
        assert PARAMPARA == 37

    def test_quarters(self):
        assert QUARTERS == 4

    def test_hare_positions(self):
        assert HARE_POSITIONS == frozenset({0, 2, 6, 7, 8, 10, 14, 15})

    def test_krishna_positions(self):
        assert KRISHNA_POSITIONS == frozenset({1, 3, 4, 5})

    def test_rama_positions(self):
        assert RAMA_POSITIONS == frozenset({9, 11, 12, 13})

    def test_word_pattern(self):
        from mahaclaw.manas import WORD_PATTERN
        assert WORD_PATTERN == ("H", "K", "H", "K", "K", "K", "H", "H",
                                "H", "R", "H", "R", "R", "R", "H", "H")


class TestSynthTransform:
    """MahaModularSynth transform must be deterministic."""

    def test_deterministic(self):
        assert _synth_transform(42) == _synth_transform(42)

    def test_different_inputs(self):
        assert _synth_transform(0) != _synth_transform(1)

    def test_output_in_mod_space(self):
        """Quantum preset outputs in range 0..MAHA_QUANTUM-1."""
        for seed in (0, 1, 42, 137, 1000, 999999):
            result = _synth_transform(seed)
            assert 0 <= result < MAHA_QUANTUM


class TestShabdaVibration:
    """Shabda phonetic vibration must be deterministic."""

    def test_deterministic(self):
        assert _text_to_vibration_sum("hello") == _text_to_vibration_sum("hello")

    def test_case_insensitive(self):
        """text_to_vibration uses text_lower internally."""
        assert _text_to_vibration_sum("Hello") == _text_to_vibration_sum("hello")

    def test_different_texts_differ(self):
        assert _text_to_vibration_sum("abc") != _text_to_vibration_sum("xyz")
